server:
  port: 8080
spring:
  application:
    name: sce-user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://sceserver2:9091/eureka,http://sceserver1:9090/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@